export const authConstants = {
	
	CREATE_SUCCESS: "CREATE_SUCCESS", 	
	INITIAL_SUCCESS: "INITIAL_SUCCESS",
	UPDATE_SUCCESS: "UPDATE_SUCCESS",
	DELETE_SUCCESS: "DELETE_SUCCESS",
	EDIT_SUCCESS:"EDIT_SUCCESS",
	UPDATE_QTY:"UPDATE_QTY" 
};

export const userConstants = {
  CREATE_PAGE_REQUEST: "CREATE_PAGE_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
};